### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by minhtritc97** [thanhhuy114/open_fashion#1]
<img width="124" alt="image" src="https://github.com/thanhhuy114/open_fashion/assets/48729090/e5b79d39-60d9-4938-9dd4-ad9a08c1bca3">

**Comment by NguyenThanhThuannn** [comment]
Xong UI
Đã lấy dữ liệu mẫu API cho homepage
chỉnh kích thước ảnh tương đối ổn
Chưa xử lý event
